# runai client install — Windows / PowerShell.
#
# Usage:
#   irm http://<SERVER>:<PORT>/install.ps1 | iex
#
# Mirror of scripts/runai-client-install.sh: writes
# %USERPROFILE%\.runai-hook.ps1 (a tiny stdin-pipe wrapper around
# Invoke-RestMethod), then patches %USERPROFILE%\.claude\settings.json
# UserPromptSubmit to call it. Backs up the prior settings.json to
# .runai-bak. Idempotent — re-running the installer doesn't stack hooks.

# {SERVER_URL} is substituted by the server at request time.
$ServerUrl = "{SERVER_URL}"
$HookPath = "$env:USERPROFILE\.runai-hook.ps1"
$SettingsPath = "$env:USERPROFILE\.claude\settings.json"

if ($ServerUrl -eq ("{" + "SERVER_URL" + "}") -or [string]::IsNullOrEmpty($ServerUrl)) {
    Write-Error "SERVER_URL placeholder not substituted. Pipe this through the runai server's /install.ps1 endpoint."
    exit 1
}

Write-Host "runai client install (Windows)"
Write-Host "  server: $ServerUrl"
Write-Host "  hook:   $HookPath"
Write-Host "  config: $SettingsPath"
Write-Host ""

# 1) Write the hook wrapper. Reads Claude Code's hook JSON from stdin,
#    forwards to the server with X-Runai-User header, prints server
#    response on stdout. 30s timeout + silent failure so a slow /
#    unreachable server never blocks the user's Claude Code prompt.
$hookBody = @"
# Auto-generated by runai-client-install.ps1. Overwritten on reinstall.
`$RunaiServer = "$ServerUrl"
`$ErrorActionPreference = "Continue"
try {
    `$payload = [Console]::In.ReadToEnd()
    `$resp = Invoke-RestMethod ``
        -Method Post ``
        -Uri "`$RunaiServer/recommend" ``
        -Headers @{ 'Content-Type' = 'application/json'; 'X-Runai-User' = "`$env:USERNAME@`$env:COMPUTERNAME" } ``
        -Body `$payload ``
        -TimeoutSec 30
    Write-Output `$resp
} catch {
    # Silent fail: do not block Claude Code prompt on server hiccups.
}
"@
$hookBody | Set-Content -Path $HookPath -Encoding utf8
Write-Host "wrote $HookPath"

# 2) Patch settings.json.
$claudeDir = Split-Path $SettingsPath
if (-not (Test-Path $claudeDir)) {
    New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
}
if (Test-Path $SettingsPath) {
    Copy-Item $SettingsPath "$SettingsPath.runai-bak" -Force
    Write-Host "backed up existing settings.json -> $SettingsPath.runai-bak"
    $raw = Get-Content $SettingsPath -Raw
    if ([string]::IsNullOrWhiteSpace($raw)) { $raw = "{}" }
    try {
        $parsed = $raw | ConvertFrom-Json
    } catch {
        Write-Warning "settings.json was not valid JSON, replacing with empty object"
        $parsed = New-Object PSObject
    }
} else {
    $parsed = New-Object PSObject
}

# Recursively convert PSCustomObject -> nested hashtable so we can mutate
# arrays / add keys without PSCustomObject quirks.
function ConvertTo-RunaiHashtable($obj) {
    if ($null -eq $obj) { return $null }
    if ($obj -is [PSCustomObject]) {
        $h = @{}
        foreach ($p in $obj.PSObject.Properties) {
            $h[$p.Name] = ConvertTo-RunaiHashtable $p.Value
        }
        return $h
    }
    if ($obj -is [System.Collections.IEnumerable] -and -not ($obj -is [string])) {
        $arr = @()
        foreach ($item in $obj) { $arr += ,(ConvertTo-RunaiHashtable $item) }
        return ,$arr
    }
    return $obj
}

$data = ConvertTo-RunaiHashtable $parsed
if ($null -eq $data -or -not ($data -is [hashtable])) { $data = @{} }
if (-not $data.ContainsKey('hooks')) { $data.hooks = @{} }
if (-not $data.hooks.ContainsKey('UserPromptSubmit')) { $data.hooks.UserPromptSubmit = @() }

# Claude Code on Windows invokes hook commands via the shell of its own
# choice. PowerShell -File <path> is the most portable form: it works
# whether the host is cmd.exe, PowerShell, or pwsh.
$hookCmd = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$HookPath`""

# Idempotent: skip if our exact command is already present.
$already = $false
foreach ($g in $data.hooks.UserPromptSubmit) {
    if ($null -ne $g -and $g.ContainsKey('hooks')) {
        foreach ($h in @($g.hooks)) {
            if ($null -ne $h -and $h.command -eq $hookCmd) { $already = $true; break }
        }
    }
    if ($already) { break }
}

if (-not $already) {
    $newGroup = @{ hooks = @(@{ type = "command"; command = $hookCmd }) }
    $data.hooks.UserPromptSubmit = @($data.hooks.UserPromptSubmit + $newGroup)
    Write-Host "patched UserPromptSubmit hook"
} else {
    Write-Host "hook already present (no-op)"
}

$data | ConvertTo-Json -Depth 20 | Set-Content -Path $SettingsPath -Encoding utf8

Write-Host ""
Write-Host "done. Open a new Claude Code session and your prompts will route through:"
Write-Host "  $ServerUrl"
Write-Host ""
Write-Host "to uninstall:"
Write-Host "  irm $ServerUrl/uninstall.ps1 | iex"
