# runai client install — Windows / PowerShell.
#
# Usage:
#   irm http://<SERVER>:<PORT>/install.ps1 | iex
#
# Mirror of scripts/runai-client-install.sh: writes
# %USERPROFILE%\.runai-hook.ps1 (a tiny stdin-pipe wrapper around
# Invoke-RestMethod), then patches %USERPROFILE%\.claude\settings.json
# UserPromptSubmit to call it. Backs up the prior settings.json to
# .runai-bak. Idempotent — re-running the installer doesn't stack hooks.

# {SERVER_URL} is substituted by the server at request time.
$ServerUrl = "{SERVER_URL}"
$HookPath = "$env:USERPROFILE\.runai-hook.ps1"
$SettingsPath = "$env:USERPROFILE\.claude\settings.json"

if ($ServerUrl -eq ("{" + "SERVER_URL" + "}") -or [string]::IsNullOrEmpty($ServerUrl)) {
    Write-Error "SERVER_URL placeholder not substituted. Pipe this through the runai server's /install.ps1 endpoint."
    exit 1
}

Write-Host "runai client install (Windows)"
Write-Host "  server: $ServerUrl"
Write-Host "  hook:   $HookPath"
Write-Host "  config: $SettingsPath"
Write-Host ""

# 1) Write the hook wrapper. Reads Claude Code's hook JSON from stdin,
#    forwards to the server with X-Runai-User header, prints server
#    response on stdout. 30s timeout + silent failure so a slow /
#    unreachable server never blocks the user's Claude Code prompt.
$hookBody = @"
# Auto-generated by runai-client-install.ps1. Overwritten on reinstall.
# Force UTF-8 on stdin / stdout / Invoke-RestMethod body — the Claude Code
# hook protocol uses UTF-8 JSON, but PowerShell defaults to the Windows
# console codepage (CP936 in zh-CN, CP1252 in en-US). Without these the
# Chinese characters in the user prompt arrive on the server as '?',
# routing breaks and the router LLM receives '???'. The output side has
# the same issue: hook output goes back to Claude Code, so reasoning /
# skill descriptions must also stay UTF-8.
`$ErrorActionPreference = "Continue"
[Console]::InputEncoding = [System.Text.UTF8Encoding]::new(`$false)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new(`$false)
`$OutputEncoding = [System.Text.UTF8Encoding]::new(`$false)

`$RunaiServer = "$ServerUrl"
try {
    # Read stdin as raw UTF-8 bytes (don't trust [Console]::In default
    # codepage even after setting InputEncoding above — re-open the
    # underlying stream to be safe).
    `$stdin = [Console]::OpenStandardInput()
    `$reader = New-Object System.IO.StreamReader(`$stdin, [System.Text.UTF8Encoding]::new(`$false))
    `$payload = `$reader.ReadToEnd()

    # Encode body as UTF-8 bytes for Invoke-RestMethod so the HTTP body
    # is exactly the bytes Claude Code wrote, not a re-encoded version.
    `$bodyBytes = [System.Text.Encoding]::UTF8.GetBytes(`$payload)

    `$resp = Invoke-RestMethod ``
        -Method Post ``
        -Uri "`$RunaiServer/recommend" ``
        -ContentType "application/json; charset=utf-8" ``
        -Headers @{ 'X-Runai-User' = "`$env:USERNAME@`$env:COMPUTERNAME" } ``
        -Body `$bodyBytes ``
        -TimeoutSec 30
    # Emit response as UTF-8 bytes via stdout (bypass PS string encoding).
    `$respBytes = [System.Text.Encoding]::UTF8.GetBytes(`$resp)
    [Console]::OpenStandardOutput().Write(`$respBytes, 0, `$respBytes.Length)
} catch {
    # Silent fail: do not block Claude Code prompt on server hiccups.
}
"@
# Write hook script as UTF-8 NO BOM. PowerShell 5.1's `-Encoding utf8`
# writes a BOM, which breaks the `#requires` / shebang convention and
# can confuse some shells; PS Core's `utf8NoBOM` isn't available on 5.1.
# Use raw .NET writer for portability across PS 5.1 and 7+.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($HookPath, $hookBody, $utf8NoBom)
Write-Host "wrote $HookPath"

# 2) Patch settings.json.
$claudeDir = Split-Path $SettingsPath
if (-not (Test-Path $claudeDir)) {
    New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
}
if (Test-Path $SettingsPath) {
    Copy-Item $SettingsPath "$SettingsPath.runai-bak" -Force
    Write-Host "backed up existing settings.json -> $SettingsPath.runai-bak"
    $raw = Get-Content $SettingsPath -Raw
    if ([string]::IsNullOrWhiteSpace($raw)) { $raw = "{}" }
    try {
        $parsed = $raw | ConvertFrom-Json
    } catch {
        Write-Warning "settings.json was not valid JSON, replacing with empty object"
        $parsed = New-Object PSObject
    }
} else {
    $parsed = New-Object PSObject
}

# Recursively convert PSCustomObject -> nested hashtable so we can mutate
# arrays / add keys without PSCustomObject quirks.
function ConvertTo-RunaiHashtable($obj) {
    if ($null -eq $obj) { return $null }
    if ($obj -is [PSCustomObject]) {
        $h = @{}
        foreach ($p in $obj.PSObject.Properties) {
            $h[$p.Name] = ConvertTo-RunaiHashtable $p.Value
        }
        return $h
    }
    if ($obj -is [System.Collections.IEnumerable] -and -not ($obj -is [string])) {
        $arr = @()
        foreach ($item in $obj) { $arr += ,(ConvertTo-RunaiHashtable $item) }
        return ,$arr
    }
    return $obj
}

$data = ConvertTo-RunaiHashtable $parsed
if ($null -eq $data -or -not ($data -is [hashtable])) { $data = @{} }
if (-not $data.ContainsKey('hooks')) { $data.hooks = @{} }
if (-not $data.hooks.ContainsKey('UserPromptSubmit')) { $data.hooks.UserPromptSubmit = @() }

# Claude Code on Windows invokes hook commands via cmd.exe by default.
# Wrap with `chcp 65001 >NUL & powershell ...` to switch the console
# codepage to UTF-8 BEFORE PowerShell takes stdin — without it the JSON
# from Claude Code is already munged through CP936/CP1252 by the time
# our hook script runs, no in-script encoding override can recover the
# original bytes. `chcp 65001` is the well-known Windows-UTF-8 idiom.
$hookCmd = "chcp 65001 >NUL & powershell -NoProfile -ExecutionPolicy Bypass -File `"$HookPath`""

# Idempotent: skip if our exact command is already present.
$already = $false
foreach ($g in $data.hooks.UserPromptSubmit) {
    if ($null -ne $g -and $g.ContainsKey('hooks')) {
        foreach ($h in @($g.hooks)) {
            if ($null -ne $h -and $h.command -eq $hookCmd) { $already = $true; break }
        }
    }
    if ($already) { break }
}

if (-not $already) {
    $newGroup = @{ hooks = @(@{ type = "command"; command = $hookCmd }) }
    $data.hooks.UserPromptSubmit = @($data.hooks.UserPromptSubmit + $newGroup)
    Write-Host "patched UserPromptSubmit hook"
} else {
    Write-Host "hook already present (no-op)"
}

# settings.json also UTF-8 no BOM — Claude Code parses it with UTF-8 by
# default and a BOM trips some JSON readers.
[System.IO.File]::WriteAllText($SettingsPath, ($data | ConvertTo-Json -Depth 20), $utf8NoBom)

Write-Host ""
Write-Host "done. Open a new Claude Code session and your prompts will route through:"
Write-Host "  $ServerUrl"
Write-Host ""
Write-Host "to uninstall:"
Write-Host "  irm $ServerUrl/uninstall.ps1 | iex"
