#!/usr/bin/env bash
# runai client install — registers a Claude Code UserPromptSubmit hook that
# proxies every prompt to a remote runai server. After this script runs,
# every Claude Code session on this machine gets skill recommendations
# generated by the server (no local runai binary needed).
#
# Usage:
#   curl -fsSL http://<SERVER>:<PORT>/install | bash
#
# What this does:
#   1) Writes ~/.runai-hook.sh — a small bash wrapper that curls the server.
#   2) Patches ~/.claude/settings.json to call that script on UserPromptSubmit.
#      The original settings.json is backed up to .runai-bak first.
#   3) Prints how to uninstall.
#
# What this does NOT do:
#   - Install any binary.
#   - Modify anything outside ~/.runai-hook.sh and ~/.claude/settings.json.
#   - Touch your existing hooks — runai's entry is appended, others are kept.
#
# Uninstall: curl -fsSL http://<SERVER>:<PORT>/uninstall | bash

set -euo pipefail

# {SERVER_URL} is substituted by the server at request time.
SERVER_URL="{SERVER_URL}"
HOOK_PATH="$HOME/.runai-hook.sh"
SETTINGS_PATH="$HOME/.claude/settings.json"

if [[ "$SERVER_URL" == "{""SERVER_URL""}" || -z "$SERVER_URL" ]]; then
  echo "runai-install: SERVER_URL placeholder was not substituted." >&2
  echo "did you curl this script directly from the runai server's /install endpoint?" >&2
  exit 1
fi

echo "runai client install"
echo "  server: $SERVER_URL"
echo "  hook:   $HOOK_PATH"
echo "  config: $SETTINGS_PATH"
echo

# 1) Write the hook wrapper. The wrapper:
#    - Pipes Claude Code's hook JSON straight to /recommend.
#    - Adds X-Runai-User: {user}@{host} for per-user session prefixing on the server.
#    - Times out at 30s and falls back to empty output so a slow/unreachable
#      server never blocks the user's Claude Code prompt.
cat > "$HOOK_PATH" <<HOOK
#!/usr/bin/env bash
# Auto-generated by runai-client-install. Edit at your own risk; running
# the installer again overwrites this file.
RUNAI_SERVER="$SERVER_URL"
curl -s --max-time 30 \\
  -X POST "\$RUNAI_SERVER/recommend" \\
  -H "Content-Type: application/json" \\
  -H "X-Runai-User: \$USER@\$(hostname -s)" \\
  --data-binary @- \\
  2>/dev/null || true
HOOK
chmod +x "$HOOK_PATH"
echo "wrote $HOOK_PATH"

# 2) Patch ~/.claude/settings.json to call the hook. Idempotent: if the entry
#    already exists, leave it alone. Original file is backed up first.
mkdir -p "$(dirname "$SETTINGS_PATH")"
if [[ -f "$SETTINGS_PATH" ]]; then
  cp "$SETTINGS_PATH" "${SETTINGS_PATH}.runai-bak"
  echo "backed up existing settings.json → ${SETTINGS_PATH}.runai-bak"
else
  echo '{}' > "$SETTINGS_PATH"
fi

# Use python3 (ships on macOS by default) to do a structured JSON edit.
# Avoids fragile sed/awk on indented JSON.
python3 - "$SETTINGS_PATH" "$HOOK_PATH" <<'PY'
import json
import sys

settings_path = sys.argv[1]
hook_path = sys.argv[2]
hook_cmd = hook_path  # absolute path; Claude Code runs it directly

with open(settings_path) as f:
    try:
        data = json.load(f)
    except json.JSONDecodeError:
        data = {}

hooks = data.setdefault('hooks', {})
ups = hooks.setdefault('UserPromptSubmit', [])

# Look for an existing entry that points at our hook script. If we find
# one, leave it; otherwise append. This makes re-running the installer a
# no-op rather than stacking duplicate hooks.
already = False
for group in ups:
    for h in group.get('hooks', []):
        if h.get('command') == hook_cmd:
            already = True
            break
    if already:
        break

if not already:
    ups.append({'hooks': [{'type': 'command', 'command': hook_cmd}]})

with open(settings_path, 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')

print('patched UserPromptSubmit hook' if not already else 'hook already present (no-op)')
PY

echo
echo "done. open a new Claude Code session and your prompts will route through:"
echo "  $SERVER_URL"
echo
echo "to uninstall:"
echo "  curl -fsSL $SERVER_URL/uninstall | bash"
